export const mockBlogData = [
  {
    id: 1,
    title: "Blog Post 1",
    createdAt: "2023-09-01",
    editedAt: "2023-09-02",
    status: "published",
    likes: 50,
    views: 100,
    comments: 3,
    imageUrl: "https://via.placeholder.com/300x200",
    details: "This post is about cybersecurity, and the process how it protects a network from malicious content.",
    category: "cybersecurity",
  },
  {
    id: 2,
    title: "Blog Post 2",
    createdAt: "2023-09-05",
    editedAt: null,
    status: "draft",
    likes: 10,
    views: 500,
    comments: 5,
    imageUrl: "https://via.placeholder.com/300x200",
    details: "This post is about cybersecurity, and the process how it protects a network from malicious content.",
    category: "cybersecurity",
  },
  {
    id: 3,
    title: "Blog Post 2",
    createdAt: "2023-09-05",
    editedAt: null,
    status: "draft",
    likes: 10,
    views: 240,
    comments: 7,
    imageUrl: "https://via.placeholder.com/300x200",
    details: "This post is about cybersecurity, and the process how it protects a network from malicious content.",
    category: "cybersecurity",
  },
  // Add more mock data as needed
];
